version: '3'

services:
  elk:
    container_name: elk  
    build: .
    environment:
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
      LOGSTASH_START: 0
      KIBANA_CONNECT_RETRY: 60
    ports:
      - "9200:9200"
      - "5601:5601"
    volumes:
      - ./elk-post-hooks.sh:/usr/local/bin/elk-post-hooks.sh
      - ./mappings.json:/_config/mappings.json
      - ./kibana:/_config/kibana/
    healthcheck:
        test: ["CMD", "curl", "-q", "http://localhost:5601"]
    networks:
      - elknet

networks:
  elknet:

